### ISSUE TITLE
Broken runtime on vanilla installation

### ISSUE THREAD

**Issue by louis-jaris** [Modern-Treasury/modern-treasury-python#570]
It looks like the `httpx` dependency is not properly pinned.

How to reproduce:
```bash
cd /tmp/

# Clean and vanilla venv
rm -rf .venv && python3.13 -m venv .venv && source .venv/bin/activate && python -m pip install modern-treasury

# It fails
python -c 'import modern_treasury; client = modern_treasury.ModernTreasury(api_key="123", organization_id="456")'
```

The error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import modern_treasury; client = modern_treasury.ModernTreasury(api_key="123", organization_id="456")
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/.venv/lib/python3.13/site-packages/modern_treasury/_client.py", line 169, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        version=__version__,
        ^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        _strict_response_validation=_strict_response_validation,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/private/tmp/.venv/lib/python3.13/site-packages/modern_treasury/_base_client.py", line 856, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ~~~~~~~~~~~~~~~~~~~~~~^
        base_url=base_url,
        ^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        follow_redirects=True,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/private/tmp/.venv/lib/python3.13/site-packages/modern_treasury/_base_client.py", line 754, in __init__
    super().__init__(**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

A `pip freeze`:

```
annotated-types==0.7.0
anyio==4.7.0
certifi==2024.8.30
distro==1.9.0
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
idna==3.10
modern-treasury==1.43.0
pydantic==2.10.3
pydantic-core==2.27.1
sniffio==1.3.1
typing-extensions==4.12.2
```

---

It must be related to an API change of `httpx` clients -- `proxies` renamed to `proxy`.

**Comment by RobertCraigie** [comment]
Please try again with `1.43.1`, this should already be fixed!

**Comment by RobertCraigie** [comment]
ah thanks for reporting, looks like publishing to PyPi failed, sorry we missed that.

In the meantime you can workaround this by installing `httpx<0.28` or by installing the SDK through github.

**Comment by RobertCraigie** [comment]
@louis-jaris `v1.44.0` has just been released, can you try again?

**Comment by louis-jaris** [comment]
`1.44.0` now get picked by default, and it contains the fix, thank you 👌
